<page>
    <h1>Create Call</h1>
    <config id="CREATE_DESC"/>
    <h3>Example</h3>
    <syntax-highlight mark="6-17">
        from ntgcalls import NTgCalls
        ...

        app = NTgCalls()

        params = await app.create_call(
            -1001185324811,
        )
    </syntax-highlight>
    <separator/>
    <h2>Details</h2>
    <category-title noref="true">
        <shi>async</shi> <ref src="method">NTgCalls.<sb>create_call</sb></ref>() <shi>-> str</shi>
    </category-title>
    <subtext>
        <config id="CREATE_DESC2"/>
        <br/>
        <category>
            <pg-title>PARAMETERS</pg-title>
            <subtext>
                <config id="ARG_INT_ID"/>
            </subtext>
        </category>
        <br/>
        <category>
            <pg-title>RAISES</pg-title>
            <subtext>
                <category-title>exception <ref>ntgcalls.<sb>ConnectionError</sb></ref></category-title>
                <subtext><text>You are attempting to init an already existent Group Call.</text></subtext>
                <config id="NTG_STREAM_EXCEPTIONS"/>
            </subtext>
        </category>
    </subtext>
</page>